### PR TITLE
Correct word errors

### PR DESCRIPTION
**Pull request by CCpro10**
#### What type of PR is this?
docs: Documentation only changes

#### What this PR does / why we need it (en: English/zh: Chinese):

en:  Correct word errors
zh:  修复拼写错误

### CODE REVIEW

**Comment by CCpro10** [comment]
@chenzhuoyu

**Comment by chenzhuoyu** [comment]
@CCpro10 请先签 CLA

**Comment by CCpro10** [comment]
> @CCpro10 请先签 CLA

已完成

**Comment by CCpro10** [comment]
@chenzhuoyu

**Review by YangruiEmma — APPROVED** [review]

**Pull request merged**
